WITH CTE as (

SELECT
TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
--DAYNAME((TO_TIMESTAMP(STARTED_AT))) AS DAY_STARTED_AT

{{day_type('STARTED_AT')}} AS DAY_TYPE  ,

{{get_season('STARTED_AT')}} AS SEASON_OF_YEAR,

{{function1('STARTED_AT')}} AS STATE



FROM
{{ source('demo', 'bike') }}
WHERE STARTED_AT != 'started_at'
)

SELECT * FROM 
CTE